### ISSUE TITLE
Improving TLS session to elasticsearch sink in dataflow

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/beam-deployment#1]
# JIRA Issue

https://issues.apache.org/jira/browse/BEAM-7519

# Tasks

- [ ]  Set elasticsearch in minikube
- [ ]  Sample direct runner using elasticsearch sink without TLS
- [ ]  with TLS session
- [ ] Post comment to JIRA
