### ISSUE TITLE
Test apache beam on spark3 cluster

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/beam-deployment#3]
Blocked by https://issues.apache.org/jira/browse/BEAM-12762

# ToDo

- [x] Prepare spark cluster
- [x] Prepare Harness container
- [x] Prepare Job container
- [x] Submit pipeline
